import { describe, expect, test } from 'bun:test'
import { mkdtempSync, readFileSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join, resolve } from 'node:path'

const scriptPath = resolve(import.meta.dir, '..', 'scripts', 'bump-version.ts')

describe('bump-version script', () => {
	test('updates Cargo.lock with Windows line endings', () => {
		const root = mkdtempSync(join(tmpdir(), 'agent-toolkit-bump-version-'))
		writeFileSync(rootFile(root, 'package.json'), JSON.stringify({ version: '0.1.0' }))
		writeFileSync(
			rootFile(root, 'Cargo.toml'),
			[
				'[workspace]',
				'resolver = "2"',
				'',
				'[workspace.package]',
				'version = "0.1.0"',
				'',
			].join('\n'),
		)
		writeFileSync(
			rootFile(root, 'Cargo.lock'),
			[
				'# This file is automatically @generated by Cargo.',
				'version = 4',
				'',
				'[[package]]',
				'name = "agent-toolkit"',
				'version = "0.1.0"',
				'dependencies = [',
				' "agent-toolkit-core",',
				']',
				'',
				'[[package]]',
				'name = "agent-toolkit-core"',
				'version = "0.1.0"',
				'',
			].join('\r\n'),
		)

		const result = Bun.spawnSync({
			cmd: ['bun', scriptPath, '0.1.1'],
			cwd: root,
			stderr: 'pipe',
			stdout: 'pipe',
		})

		expect(result.exitCode).toBe(0)
		expect(readFileSync(rootFile(root, 'Cargo.lock'), 'utf8')).toContain('version = "0.1.1"')
	})
})

function rootFile(root: string, path: string): string {
	return join(root, path)
}
